name: Build ve Yayınla

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle'a izin ver
        run: chmod +x ./gradlew

      - name: Eklentileri derle
        run: ./gradlew make makePluginsJson

      - name: builds dalına yayınla
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds
          folder: build
          single-commit: true
